# Generated by Django 2.1 on 2018-08-18 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamsApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamescore',
            old_name='date',
            new_name='game_date',
        ),
        migrations.AlterField(
            model_name='gamescore',
            name='first_team',
            field=models.CharField(default='Team1', max_length=256),
        ),
        migrations.AlterField(
            model_name='gamescore',
            name='second_team',
            field=models.CharField(default='Team2', max_length=256),
        ),
        migrations.AlterField(
            model_name='gamescore',
            name='team1',
            field=models.ForeignKey(on_delete=True, related_name='first_team', to='TeamsApp.Team'),
        ),
        migrations.AlterField(
            model_name='gamescore',
            name='team2',
            field=models.ForeignKey(on_delete=True, related_name='second_team', to='TeamsApp.Team'),
        ),
        migrations.AlterField(
            model_name='player',
            name='age',
            field=models.IntegerField(default=18),
        ),
        migrations.AlterField(
            model_name='player',
            name='number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='team',
            field=models.ForeignKey(on_delete=True, to='TeamsApp.Team'),
        ),
    ]
