# Generated by Django 2.1 on 2018-08-18 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TeamsApp', '0003_auto_20180818_2312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamescore',
            name='first_team',
        ),
        migrations.RemoveField(
            model_name='gamescore',
            name='second_team',
        ),
    ]
